### ISSUE TITLE
Реализовать систему комментариев

### ISSUE THREAD

**Issue by s1veme** [anime-team-pet-projects/anime-summer#1]
Можно будет оставлять комментарии под комментариями, либо под аниме.
Также только автор может редактировать свой комментарий, либо удалить его.

**Comment by Cxatek18** [comment]
Почему логика views пишется в api/views.py, чем этот метод написания лучше чем в созднаном самим фреймворком "Django" файла views.py? @s1veme

**Comment by Cxatek18** [comment]
Релизовал функционал создания комментария. Прошу вас проверить @s1veme.
```python
class AddComment(viewsets.ViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Comment.objects.all()

    def create(self, request, *args, **kwargs):
        author = request.user
        if request.data.get('parent'):
            parent = request.data.get('parent')
            parent_comment = Comment.objects.get(id=int(parent))
            content_id = request.data.get('content_id')
            anime = ContentType.objects.get_for_model(Anime)
            text = request.data.get('text_comment')
            Comment.objects.create(
                parent=parent_comment, text_comment=text, author=author,
                content_type=anime, object_id=content_id,
            )
        else:
            content_id = request.data.get('content_id')
            anime = ContentType.objects.get_for_model(Anime)
            text = request.data.get('text_comment')
            Comment.objects.create(
                text_comment=text, author=author,
                content_type=anime, object_id=content_id,
            )

        return Response({
            "Comment created": "ok"
        }, status=status.HTTP_201_CREATED)
```
Конечно версия не окончательная так как потом добавиться Manga и скорее всего логика создания комментария будет немного другая.

**Comment by s1veme** [comment]
> Релизовал функционал создания комментария. Прошу вас проверить @s1veme.
> 
> ```python
> class Comment(viewsets.ViewSet):
>     permission_classes = (IsAuthenticated,)
>     queryset = Comment.objects.all()
> 
>     def create(self, request, *args, **kwargs):
>         author = request.user
>         if request.data.get('parent'):
>             parent = request.data.get('parent')
>             parent_comment = Comment.objects.get(id=int(parent))
>             content_id = request.data.get('content_id')
>             anime = ContentType.objects.get_for_model(Anime)
>             text = request.data.get('text_comment')
>             Comment.objects.create(
>                 parent=parent_comment, text_comment=text, author=author,
>                 content_type=anime, object_id=content_id,
>             )
>         else:
>             content_id = request.data.get('content_id')
>             anime = ContentType.objects.get_for_model(Anime)
>             text = request.data.get('text_comment')
>             Comment.objects.create(
>                 text_comment=text, author=author,
>                 content_type=anime, object_id=content_id,
>             )
> 
>         return Response({
>             "Comment created": "ok"
>         }, status=status.HTTP_201_CREATED)
> ```
> 
> Конечно версия не окончательная так как потом добавиться Manga и скорее всего логика создания комментария будет немного другая.

Если оно работает, то отправляй PR, а там разберёмся.

**Comment by s1veme** [comment]
> торый написал это

Прикрепи полный код View.

**Comment by Cxatek18** [comment]
Уже разобрался сам, спасибо.
